/* Actual browser controls, audio threads, offline file loading and downloads. */
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const target='file://'+path.resolve(__dirname,'../../../dist/instruments/lucky-dreamer.html');
const out=path.join(__dirname,'browser-evidence');fs.mkdirSync(out,{recursive:true});
const report={at:new Date().toISOString(),target:'dist/instruments/lucky-dreamer.html',browsers:[],limits:['Desktop Chromium and WebKit are not physical iPhone/Safari hardware.','No external MIDI device or human listening preference is established.']};
const canonical=w=>JSON.stringify(w.events.filter(e=>e.ln==='lead'));
async function inspect(kind){
 let browser,context;const result={engine:kind,checks:[],errors:[],requests:[]};
 try{
  browser=await pw[kind].launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true});const page=await context.newPage();
  page.on('pageerror',e=>result.errors.push(e.message));page.on('request',req=>{if(/^https?:/.test(req.url()))result.requests.push(req.url());});
  await page.goto(target);await page.waitForFunction(()=>!!window.LuckyDreamer);assert.equal(await page.title(),'Lucky Dreamer · DRINOMAN');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);result.checks.push('standalone initial render');
  await page.selectOption('#style','bap');const first=await page.evaluate(()=>JSON.stringify(LuckyDreamer.getWorld().events));await page.click('#melody');const second=await page.evaluate(()=>JSON.stringify(LuckyDreamer.getWorld().events));assert.notEqual(first,second);await page.click('#undo');assert.equal(await page.evaluate(()=>JSON.stringify(LuckyDreamer.getWorld().events)),first);result.checks.push('melody changes and undo returns exact score');
  await page.locator('#band-details>summary').click();await page.getByRole('button',{name:'Keep Melody when rolling',exact:true}).click();const kept=await page.evaluate(()=>JSON.stringify(LuckyDreamer.getWorld().events.filter(e=>e.ln==='lead')));await page.click('#roll');assert.equal(await page.evaluate(()=>JSON.stringify(LuckyDreamer.getWorld().events.filter(e=>e.ln==='lead'))),kept);result.checks.push('kept melody survives whole-band roll');
  await page.getByRole('button',{name:'Keep Melody when rolling',exact:true}).click();await page.locator('#band-details>summary').click();
  await page.getByRole('button',{name:'Play band',exact:true}).click();await page.waitForFunction(()=>LuckyDreamer.getState().stats.clock>50000,{},{timeout:20000});result.audio=await page.evaluate(()=>LuckyDreamer.getState());assert.equal(result.audio.playing,true);assert.equal(result.audio.audioState,'running');assert.equal(result.audio.stats.nonFinite,0);assert.ok(result.audio.stats.peak>.001);result.checks.push('actual Web Audio playback with nonzero sample peak');
  await page.evaluate(()=>{const end=performance.now()+700;while(performance.now()<end){};});await page.waitForTimeout(400);const afterStall=await page.evaluate(()=>LuckyDreamer.getState());assert.ok(afterStall.stats.clock>result.audio.stats.clock);assert.equal(afterStall.stats.nonFinite,0);result.checks.push('main-thread stall did not halt sample clock');
  await page.keyboard.press('Space');await page.waitForTimeout(650);const stopped=await page.evaluate(()=>LuckyDreamer.getState());assert.equal(stopped.playing,false);assert.equal(stopped.audioState,'suspended');assert.equal(stopped.stats.playing,false);result.checks.push('space stops audio and parks context');
  await page.locator('#keyboard-details>summary').click();await page.keyboard.down('a');await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().liveNotes),1);await page.keyboard.up('a');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().liveNotes),0);
  const key=page.locator('#keyboard [data-note="64"]');const box=await key.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height-16);await page.mouse.down();await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().liveNotes),1);await page.mouse.up();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().liveNotes),0);result.checks.push('keyboard and pointer notes release cleanly');
  await page.locator('#save-details>summary').click();let pending=page.waitForEvent('download');await page.click('#midi');let download=await pending;const midi=path.join(out,kind+'-generated.mid');await download.saveAs(midi);assert.equal(fs.readFileSync(midi).toString('ascii',0,4),'MThd');result.checks.push('generated MIDI download is a real MIDI file');
  pending=page.waitForEvent('download');await page.click('#recipe-save');download=await pending;const recipePath=path.join(out,kind+'-recipe.json');await download.saveAs(recipePath);const recipe=JSON.parse(fs.readFileSync(recipePath));await page.click('#roll');await page.setInputFiles('#recipe-file',recipePath);await page.waitForFunction(seed=>LuckyDreamer.getState().recipe.seed===seed,recipe.seed);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().recipe.seed),recipe.seed);result.checks.push('recipe export and import');
  await page.evaluate(()=>{document.getElementById('save-details').open=false;document.getElementById('keyboard-details').open=false;});await page.screenshot({path:path.join(out,kind+'-desktop.png'),fullPage:true});
  for(const width of [320,390,768]){
   await page.setViewportSize({width,height:900});await page.evaluate(()=>{document.getElementById('band-details').open=true;document.getElementById('keyboard-details').open=true;});await page.waitForTimeout(80);const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.width,JSON.stringify(geometry));if(width===390)await page.screenshot({path:path.join(out,kind+'-mobile.png'),fullPage:true});
  }result.checks.push('320/390/768 px layouts including expanded controls');
  await page.evaluate(()=>window.dispatchEvent(new Event('midiroom:panic')));await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().playing),false);await page.evaluate(()=>window.dispatchEvent(new Event('midiroom:dispose')));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>LuckyDreamer.getState().destroyed),true);result.checks.push('host panic and dispose lifecycle');
  assert.deepEqual(result.errors,[]);assert.deepEqual(result.requests,[]);result.pass=true;
 }catch(error){result.pass=false;result.failure=String(error.stack||error);}
 finally{if(context)await context.close();if(browser)await browser.close();}
 return result;
}
(async()=>{for(const kind of ['chromium','webkit']){const result=await inspect(kind);report.browsers.push(result);console.log(kind,JSON.stringify(result));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}if(report.browsers.some(r=>!r.pass))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
