#!/usr/bin/env python3
"""Build a scoped, content-versioned offline cache; never cache imported private files."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1];dist=root/'dist'
names=['index.html','style.css','app.js','catalog.js','bridge.js','loader.js','midi.js','instrument-bus.js','surface-router.js','plugin-contract.js','wish-config.js','wish.js','icon.svg','icon-192.png','icon-512.png','manifest.webmanifest']
names += [str(p.relative_to(dist)) for p in sorted((dist/'instruments').glob('*.html'))]
names += [str(p.relative_to(dist)) for p in sorted((dist/'licenses').glob('*')) if p.is_file()]
names=[n for n in names if (dist/n).is_file()]
fingerprint=hashlib.sha256()
for name in names:fingerprint.update(name.encode());fingerprint.update((dist/name).read_bytes())
version=fingerprint.hexdigest()[:16]
source="""/* Generated by build-offline.py. Built-ins only; user instruments and exports are never cached. */
const VERSION=__VERSION__;
const BASE=new URL('./',self.location.href),PREFIX='midi-room:'+BASE.pathname+':',CACHE=PREFIX+VERSION,FILES=__FILES__;
const URLS=FILES.map(file=>new URL(file,BASE).href),ALLOWED=new Set(URLS);
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const cache=await caches.open(CACHE);await cache.addAll(URLS.map(url=>new Request(url,{cache:'reload'})));
})()));
// New versions wait. Only the user's Update and reload action sends this message.
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE_UPDATE')self.skipWaiting();});
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const key of await caches.keys())if(key.startsWith(PREFIX)&&key!==CACHE)await caches.delete(key);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);
 if(request.method!=='GET'||url.origin!==BASE.origin||!url.pathname.startsWith(BASE.pathname))return;
 url.hash='';url.search='';if(url.pathname===BASE.pathname)url.pathname+='index.html';
 if(!ALLOWED.has(url.href))return;
 event.respondWith((async()=>{const cache=await caches.open(CACHE);return await cache.match(url.href)||fetch(request);})());
});
""".replace('__VERSION__',json.dumps(version)).replace('__FILES__',json.dumps(names))
(dist/'sw.js').write_text(source)
(root/'verification').mkdir(exist_ok=True)
(root/'verification/offline-build.json').write_text(json.dumps({'cache_version':version,'files':names,'bytes':sum((dist/n).stat().st_size for n in names),'scope':'Relative to sw.js directory; built-ins and shell only. Imported private instruments, maps and exports excluded.'},indent=2)+'\n')
print('Offline cache',version, len(names),'files')
